export const dummyNews = [
  {
    id: 1,
    category: "Frontend",
    title: "React continues to evolve",
    summary: "New improvements are making React applications faster and easier to build.",
    source: "WebDev Times",
    time: "2 hours ago",
  },
  {
    id: 2,
    category: "AI Models",
    title: "New AI models improve coding",
    summary: "Developers are using modern AI models to write and understand code faster.",
    source: "AI Daily",
    time: "3 hours ago",
  },
  {
    id: 3,
    category: "Backend",
    title: "Node.js ecosystem grows",
    summary: "New tools are improving the way developers build scalable backend systems.",
    source: "Backend Weekly",
    time: "4 hours ago",
  },
  {
    id: 4,
    category: "Dev Tools",
    title: "Vite gets faster",
    summary: "Modern frontend tooling continues to improve development experience.",
    source: "Dev Tools",
    time: "5 hours ago",
  },
  {
    id: 5,
    category: "Design",
    title: "Design systems become essential",
    summary: "More development teams are adopting reusable design systems.",
    source: "Design Daily",
    time: "6 hours ago",
  },
  {
    id: 6,
    category: "Strategy",
    title: "Developers focus on AI workflows",
    summary: "AI-assisted development is changing how teams plan and build products.",
    source: "Tech Strategy",
    time: "7 hours ago",
  },
];